auth:
  user_registration_enabled: true
  password_policy:
    min_length: 8
    max_length: 64
    require_uppercase: true
    require_lowercase: true
    require_numbers: true
    require_symbols: false
