apiVersion: apps/v1
kind: Deployment
metadata:
  name: pentesting-auth
  labels:
    app: pentesting
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pentesting
      tier: backend
  template:
    metadata:
      labels:
        app: pentesting
        tier: backend
    spec:
      containers:
        - name: pentesting-auth
          image: pentesting-auth:latest
          ports:
            - containerPort: 5001
          env:
            - name: AUTH_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: pentesting-secrets
                  key: auth-secret-key
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: pentesting-secrets
                  key: database-url
          volumeMounts:
            - name: config-volume
              mountPath: /app/config
      volumes:
        - name: config-volume
          configMap:
            name: pentesting-config
