apiVersion: v1
kind: ConfigMap
metadata:
  name: logging-config
  namespace: pentesting
data:
  fluentd.conf: |
    <source>
      @type forward
      port 24224
      bind 0.0.0.0
    </source>
    <match **>
      @type forward
      <server>
        host logging-forwarder.pentesting.svc.cluster.local
        port 24224
      </server>
    </match>

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: pentesting
data:
  prometheus.yml: |
    global:
      scrape_interval: 10s
    scrape_configs:
      - job_name: prometheus
        static_configs:
          - targets: ['localhost:9090']
      - job_name: pentesting
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_container_port_number]
            action: keep
            regex: '5000'
          - source_labels: [__meta_kubernetes_pod_container_name]
            action: replace
            target_label: container_name
          - source_labels: [__meta_kubernetes_namespace]
            action: replace
            target_label: namespace
          - source_labels: [__meta_kubernetes_pod_name]
            action: replace
            target_label: pod_name
    rule_files:
      - /etc/prometheus/rules/*.rules
