apiVersion: apps/v1
kind: Deployment
metadata:
  name: pentesting-backend
  labels:
    app: pentesting
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pentesting
      tier: backend
  template:
    metadata:
      labels:
        app: pentesting
        tier: backend
    spec:
      containers:
        - name: pentesting-backend
          image: pentesting-backend:latest
          ports:
            - containerPort: 5000
          env:
            - name: FLASK_ENV
              value: production
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: pentesting-secrets
                  key: database-url
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: pentesting-secrets
                  key: aws-access-key-id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: pentesting-secrets
                  key: aws-secret-access-key
          volumeMounts:
            - name: config-volume
              mountPath: /app/config
      volumes:
        - name: config-volume
          configMap:
            name: pentesting-config
