apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: pentesting-scc
allowPrivilegedContainer: false
allowHostPorts: false
allowHostIPC: false
allowHostNetwork: false
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: MustRunAs
supplementalGroups:
  type: RunAsAny
fsGroup:
  type: RunAsAny
readOnlyRootFilesystem: true
volumes:
  - configMap
  - secret
  - emptyDir
